### ISSUE TITLE
Web Scraping Script?

### ISSUE THREAD

**Issue by Camiann** [Nishnha/Title-IX-Call-for-Comments-Analysis#1]
@Nishnha This is great work. I was wondering if you could post the script you used to scape the public comment submissions and attachments from regulations.gov.

**Comment by Camiann** [comment]
Thanks!

**Comment by Nishnha** [comment]
@Camiann,

[Here is a Gist](https://gist.github.com/Nishnha/20eeea5d7692771419d46351acc1bc5f) of the [webscraper.io](https://www.webscraper.io/) sitemap export that I used for web scraping the regulations.gov comments.

I had to remake the script, so it may differ slightly from the original one in terms of naming; functionality should be identical.

Hope this helps!
